pmb3_configuration:
  wheel_model:
    description: 'Wheel model'
    values: ['nadia', 'moog']
    default: 'moog'
  laser_model:
    description: 'Base laser model'
    values: ['no-laser', 'sick-571', 'sick-561', 'sick-551', 'hokuyo']
    default: 'sick-571'
  camera_model:
    description: 'Base camera model'
    values: ['realsense-d435']
    default: 'orbbec-astra'
